// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIlrwet8E2RKgSstHACJ_9tYlY34whcQY',
    appId: '1:981491656736:android:0d4d0f9ebd1a1bc1c67445',
    messagingSenderId: '981491656736',
    projectId: 'robo-t-scouting',
    storageBucket: 'robo-t-scouting.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGmsHNyEDCBC1DO3DT8Xq2ma8ogBPtGQg',
    appId: '1:981491656736:ios:417c971dd738cd1dc67445',
    messagingSenderId: '981491656736',
    projectId: 'robo-t-scouting',
    storageBucket: 'robo-t-scouting.appspot.com',
    androidClientId: '981491656736-0btcsmibv77u5efh4u2hhrdcdatcgfbn.apps.googleusercontent.com',
    iosClientId: '981491656736-u2t7q2j56rig9g0t8ul4q1e2cht5ra73.apps.googleusercontent.com',
    iosBundleId: 'org.emeraldcraft.scouting.emeraldscouting',
  );
}
